#
# Copyright 2025 John Harwell, All rights reserved.
#
# SPDX-License-Identifier: MIT
#

# Core packages
import shutil

# 3rd party packages
import nox

# Project packages
from sierra.core import batchroot
from tests._framework import engines, verify
from tests._framework import env as fwenv
from tests._framework.command import SierraCommand

_YAMLSIM = engines.BY_NAME["yamlsim"]


@nox.session(python=fwenv.VERSIONS, tags=["proc", "presence", "smoke"])
@fwenv.session_setup
@fwenv.session_teardown
def pseudostats_sanity(session):
    """Check that the pseudostats plugin works/doesn't crash."""
    spec = _YAMLSIM
    bc = spec.batch_criteria
    leaf = batchroot.ExpRootLeaf(bc=[bc], template_stem=spec.template_stem)
    batch_root = batchroot.ExpRoot(
        sierra_root=f"{session.env['SIERRA_ROOT']}",
        project=spec.project,
        controller=spec.controller,
        leaf=leaf,
        scenario=spec.scenario,
    ).to_path()

    def _cmd(*extra):
        c = (
            SierraCommand.from_base(session.env[spec.base_cmd_env].split())
            .set("--controller", spec.controller)
            .set("--batch-criteria", bc)
            .set_multi("--proc", ["proc.pseudostats"])
            .pipeline(1, 2, 3)
        )
        for flag, val in extra:
            c.set(flag, val)
        return c

    session.run(*_cmd().render(), silent=True)

    # Check stat outputs.
    # yamlsim intra-exp stats only. Inter-exp collation genuinely is not
    # generated by this run (a real scope limit, not laxness), so scope=
    # "per_exp". The run uses SIERRA's default center/spread, so we verify
    # whatever stat suffixes those defaults produce.
    verify.verify_stage(_YAMLSIM, 3, batch_root, max_tier=1, scope="per_exp")

    # Check raw outputs
    for exp in range(0, spec.cardinality):
        for run in range(0, spec.n_runs):
            path = batch_root / "exp-outputs" / f"c1-exp{exp}/template_run{run}_output/"
            assert (
                len(list(path.rglob("*.csv"))) > 0
            ), f"Raw data at {path} does not exist"

    shutil.rmtree(session.env["SIERRA_ROOT"])

    session.run(*_cmd(("--dataop", "move")).render(), silent=True)

    # Check stat outputs
    # yamlsim intra-exp stats only. Inter-exp collation genuinely is not
    # generated by this run (a real scope limit, not laxness), so scope=
    # "per_exp". The run uses SIERRA's default center/spread, so we verify
    # whatever stat suffixes those defaults produce.
    verify.verify_stage(_YAMLSIM, 3, batch_root, max_tier=1, scope="per_exp")

    # Check raw outputs
    for exp in range(0, spec.cardinality):
        for run in range(0, spec.n_runs):
            path = batch_root / "exp-outputs" / f"c1-exp{exp}/template_run{run}_output/"
            assert len(list(path.rglob("*.csv"))) == 0, f"Raw data at {path} exists"
