LN_fsm_interference:
  graphs:
    - src_stem: fsm-interference-counts
      dest_stem: fsm-interference-counts
      cols:
        - int_avg_exp_interference
        - cum_avg_exp_interference
        - int_avg_entered_interference
        - cum_avg_entered_interference
        - int_avg_exited_interference
        - cum_avg_exited_interference
      title: 'Swarm Inter-Robot Interference'
      legend:
        - 'Average # Robots Experiencing Interference (Interval)'
        - 'Average # Robots Experiencing Interference (Cumulative)'
        - 'Average # Robots Beginning Interference Encounter (Interval)'
        - 'Average # Robots Beginning Interference Encounter (Cumulative)'
        - 'Average # Robots Ending Interference Encounter (Interval)'
        - 'Average # Robots Ending Interference Encounter (Cumulative)'
      xlabel: 'Interval'
      ylabel: '# Robots'

    - src_stem: fsm-interference-counts
      dest_stem: fsm-interference-duration
      cols:
        - int_avg_interference_duration
        - cum_avg_interference_duration
      title: 'Swarm Interference Duration'
      legend:
        - 'Average Interference Duration (Interval)'
        - 'Average Interference Duration (Cumulative)'
      xlabel: 'Interval'
      ylabel: '# Timesteps'

LN_spatial_movement:
  graphs:
    - src_stem: spatial-movement
      dest_stem: spatial-movement-distance-all
      cols:
        - int_avg_distance_all
        - cum_avg_distance_all
      title: 'Average Per-robot Distance Traveled'
      legend:
        - 'Distance (Interval)'
        - 'Distance (Cumulative)'
      xlabel: 'Interval'
      ylabel: 'Distance (m)'

    - src_stem: spatial-movement
      dest_stem: spatial-movement-velocity-all
      cols:
        - int_avg_velocity_all
        - cum_avg_velocity_all
      title: 'Average Per-robot Velocity'
      legend:
        - 'Velocity (Interval)'
        - 'Velocity (Cumulative)'
      xlabel: 'Interval'
      ylabel: 'Velocity (cm/s)'

    - src_stem: spatial-movement
      dest_stem: spatial-movement-distance-homing
      cols:
        - int_avg_distance_homing
        - cum_avg_distance_homing
      title: 'Average Per-robot Homing distance traveled'
      legend:
        - 'Distance (Interval)'
        - 'Distance (Cumulative)'
      xlabel: 'Interval'
      ylabel: 'Distance (m)'

    - src_stem: spatial-movement
      dest_stem: spatial-movement-velocity-homing
      cols:
        - int_avg_velocity_homing
        - cum_avg_velocity_homing
      title: 'Average Per-robot Homing Velocity'
      legend:
        - 'Velocity (Interval)'
        - 'Velocity (Cumulative)'
      xlabel: 'Interval'
      ylabel: 'Velocity (cm/s)'

LN_block_acq:
  graphs:
    - src_stem: block-acq-counts
      dest_stem: block-acq-counts
      cols:
        # - int_avg_acquiring_goal
        # - cum_avg_acquiring_goal
        # - int_avg_vectoring_to_goal
        # - cum_avg_vectoring_to_goal
        # - int_avg_vectoring_to_goal
        # - cum_avg_vectoring_to_goal
        - int_avg_true_exploring_for_goal
        - cum_avg_true_exploring_for_goal
        # - int_avg_false_exploring_for_goal
        # - cum_avg_false_exploring_for_goal
      title: 'Swarm Block Acquisition'
      legend:
        # - 'Average # Robots Acquiring Blocks (Interval)'
        # - 'Average # Robots Acquiring Blocks (Cumulative)'
        # - 'Average # Robots Vectoring To Blocks (Interval)'
        # - 'Average # Robots Vectoring To Blocks (Cumulative)'
        - 'Average # Robots Exploring For Blocks (Interval)'
        - 'Average # Robots Exploring For Blocks (Cumulative)'
      #   - 'Average # Robots Falsely Exploring For Blocks (Interval)'
      #   - 'Average # Robots Falsely Exploring For Blocks (Cumulative)'
      xlabel: 'Interval'
      ylabel: '# Robots'


LN_convergence:
  graphs:
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-int-deg-raw
      cols:
        - int_avg_interact_deg_raw
      title: 'Swarm Convergence (Interaction Degree)'
      legend:
        - 'Raw'
      xlabel: 'Interval'
      ylabel: 'Degree'
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-int-deg-norm
      cols:
        - int_avg_interact_deg_norm
        - int_avg_interact_deg_converged
      title: 'Swarm Convergence (Interaction Degree)'
      legend:
        - 'Normalized'
        - 'Convergence Status'
      xlabel: 'Interval'
      ylabel: 'Degree'
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-ang-order-raw
      cols:
        - int_avg_ang_order_raw
      title: 'Swarm Convergence (Angular Order)'
      legend:
        - 'Raw'
      xlabel: 'Interval'
      ylabel: 'Value'
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-ang-order-norm
      cols:
        - int_avg_ang_order_norm
        - int_avg_ang_order_converged
      title: 'Swarm Convergence (Angular Order)'
      legend:
        - 'Normalized'
        - 'Convergence Status'
      xlabel: 'Interval'
      ylabel: 'Value'
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-pos-entropy-raw
      cols:
        - int_avg_pos_entropy_raw
      title: 'Swarm Convergence (Positional Entropy)'
      legend:
        - 'Raw'
      xlabel: 'Interval'
      ylabel: 'Value'
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-pos-entropy-norm
      cols:
        - int_avg_pos_entropy_norm
        - int_avg_pos_entropy_converged
      title: 'Swarm Convergence (Positional Entropy)'
      legend:
        - 'Normalized'
        - 'Convergence Status'
      xlabel: 'Interval'
      ylabel: 'Value'
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-task-dist-entropy-raw
      cols:
        - int_avg_task_dist_entropy_raw
      title: 'Swarm Convergence (Task Distribution Entropy)'
      legend:
        - 'Raw'
      xlabel: 'Interval'
      ylabel: 'Value'
    - src_stem: swarm-convergence
      dest_stem: swarm-conv-task-dist-entropy-norm
      cols:
        - int_avg_task_dist_entropy_norm
        - int_avg_task_dist_entropy_converged
      title: 'Swarm Convergence (Task Distribution Entropy)'
      legend:
        - 'Normalized'
        - 'Convergence Status'
      xlabel: 'Interval'
      ylabel: 'Value'

LN_population:
  graphs:
    - src_stem: tv-population
      dest_stem: tv-population-size
      cols:
        - int_avg_active_population
        - cum_avg_active_population
        - int_avg_total_population
        - cum_avg_total_population
        - max_population
      title: 'Swarm Population'
      legend:
        - 'Average Swarm Active Population (Interval)'
        - 'Average Swarm Active Population (Cumulative)'
        - 'Average Swarm Total Population (Interval)'
        - 'Average Swarm Total Population (Cumulative)'
        - 'Swarm Max Population'
      xlabel: 'Interval'
      ylabel: '# Robots'

    - src_stem: tv-population
      dest_stem: tv-population-rates
      cols:
        - int_avg_birth_rate
        - cum_avg_birth_rate
        - int_avg_death_rate
        - cum_avg_death_rate
      title: 'Swarm Population Rates'
      legend:
        - 'Average Swarm Birth Rate (Interval)'
        - 'Average Swarm Birth Rate (Cumulative)'
        - 'Average Swarm Death Rate (Interval)'
        - 'Average Swarm Death Rate (Cumulative)'
      xlabel: 'Interval'
      ylabel: 'Events/timestep'

    - src_stem: tv-population
      dest_stem: tv-population-intervals
      cols:
        - int_avg_birth_interval
        - cum_avg_birth_interval
        - int_avg_death_interval
        - cum_avg_death_interval
      title: 'Swarm Population Event Intervals'
      legend:
        - 'Average Birth Interval (Interval)'
        - 'Average Birth Interval (Cumulative)'
        - 'Average Death Interval (Interval)'
        - 'Average Death Interval (Cumulative)'
      xlabel: 'Interval'
      ylabel: 'Timestep'
