#
# Copyright 2024 John Harwell, All rights reserved.
#
# SPDX-License-Identifier: MIT
#
"""Generate heatmaps *across* multiple :term:`Experiments <Experiment>`."""

# Core packages
import logging

# 3rd party packages
import json

# Project packages
from sierra.core import types, batchroot, graphs
from sierra.core.graphs import bcbridge

_logger = logging.getLogger(__name__)


def generate(
    cmdopts: types.Cmdopts,
    pathset: batchroot.PathSet,
    targets: list[list[types.YAMLDict]],
    info: bcbridge.GraphInfo,
) -> None:
    """
    Generate heatmaps from: term:`Processed Output Data` files.
    """
    large_text = cmdopts["plot_large_text"]

    _logger.info(
        "Heatmaps from <batch_root>/%s",
        pathset.stat_interexp_root.relative_to(pathset.root),
    )

    # For each category of heatmaps we are generating
    for category in targets:

        # For each graph in each category
        for graph in category:
            # Only try to create heatmaps (duh)
            if graph["type"] != "heatmap":
                continue

            _logger.trace("\n" + json.dumps(graph, indent=4))

            graph_pathset = graphs.PathSet(
                input_root=pathset.stat_interexp_root,
                output_root=pathset.graph_interexp_root,
                batchroot=pathset.root,
                model_root=None,
            )
            # 2025-06-05 [JRH]: We always write stage {3,4} output data files as
            # .csv because that is currently SIERRA's 'native' format; this may
            # change in the future.
            graphs.heatmap(
                pathset=graph_pathset,
                input_stem=str(graph["dest"]),
                output_stem=str(graph["dest"]),
                medium="storage.csv",
                title=str(graph["title"]),
                xlabel=info.xlabel,
                ylabel=info.ylabel,
                xticklabels=info.xticklabels,
                yticklabels=info.yticklabels,
                xticks=info.xticks,
                yticks=info.yticks,
                zlabel=str(graph["zlabel"]),
                stats_center=cmdopts.get("center", "mean"),
                backend=str(graph.get("backend", cmdopts["graphs_backend"])),
                # 2026-07-24 [JRH]: We don't reference the graph config for the
                # {X,Y,Z} column names because the source CSV is generated by
                # collation in this plugin, so we KNOW it has these exact
                # columns.
                colnames=("x", "y", "z"),
                large_text=large_text,
            )


__all__ = ["generate"]
