#
# Copyright 2024 John Harwell, All rights reserved.
#
# SPDX-License-Identifier: MIT
#
"""Inter-experiment histogram generation in stage 4."""

# Core packages
import logging
import typing as tp

# 3rd party packages
import json

# Project packages
from sierra.core import types, batchroot, graphs
from sierra.core.graphs import bcbridge

_logger = logging.getLogger(__name__)


def generate(
    cmdopts: types.Cmdopts,
    pathset: batchroot.PathSet,
    targets: list[list[types.YAMLDict]],
    info: bcbridge.GraphInfo,
) -> None:
    """Generate histograms from :term:`Collated Output Data` files.

    The graphs generated by this module respect the ``--exp-range`` cmdline
    option.
    """

    _logger.info(
        "Histograms from <batchroot>/%s",
        pathset.stat_interexp_root.relative_to(pathset.root),
    )

    # For each category of histograms we are generating
    for category in targets:

        # For each graph in each category
        for graph in category:
            if graph["type"] != "histogram":
                continue

            _logger.trace("\n" + json.dumps(graph, indent=4))

            paths = graphs.PathSet(
                input_root=pathset.stat_interexp_root,
                output_root=pathset.graph_interexp_root,
                model_root=None,
                batchroot=pathset.root,
            )

            graphs.histogram(
                pathset=paths,
                input_stem=str(graph["dest"]),
                output_stem=str(graph["dest"]),
                medium="storage.csv",
                title=str(graph["title"]),
                backend=str(graph.get("backend", cmdopts["graphs_backend"])),
                xlabel=str(graph["xlabel"]),
                ylabel=str(graph["ylabel"]),
                large_text=cmdopts["plot_large_text"],
                stats_center=cmdopts.get("center", "mean"),
                # 2026-07-22 [JRH]: 'cols' selects which column is pulled from
                # each experiment during collation; the collated frame then has
                # one column *per experiment*, all of which are plotted. So the
                # selection has already been applied by the time we get here.
                cols=None,
                bins=None if graph.get("bins") is None else str(graph["bins"]),
                kind=str(graph["kind"]),
                legend=tp.cast(
                    "tp.Optional[list[str]]", graph.get("legend", info.exp_names)
                ),
            )


__all__ = ["generate"]
