#
# Copyright 2024 John Harwell, All rights reserved.
#
# SPDX-License-Identifier: MIT
#
"""Inter-experiment linegraph generation in stage 4."""

# Core packages
import logging
import typing as tp

# 3rd party packages
import json

# Project packages
from sierra.core import types, batchroot, graphs
from sierra.core.graphs import bcbridge

_logger = logging.getLogger(__name__)


def generate(
    cmdopts: types.Cmdopts,
    pathset: batchroot.PathSet,
    targets: list[list[types.YAMLDict]],
    info: bcbridge.GraphInfo,
) -> None:
    """Generate linegraphs from :term:`Collated Output Data` files.

    The graphs generated by this module respect the ``--exp-range`` cmdline
    option.
    """

    _logger.info(
        "Linegraphs from <batchroot>/%s",
        pathset.stat_interexp_root.relative_to(pathset.root),
    )

    # For each category of linegraphs we are generating
    for category in targets:

        # For each graph in each category
        for graph in category:
            if graph["type"] not in ["summary_line", "stacked_line"]:
                continue

            _logger.trace("\n" + json.dumps(graph, indent=4))

            if graph["type"] == "summary_line":
                _gen_summary_linegraph(graph, pathset, cmdopts, info)
            elif graph["type"] == "stacked_line":
                _gen_stacked_linegraph(graph, pathset, cmdopts, info)


def _gen_summary_linegraph(
    graph: types.YAMLDict,
    pathset: batchroot.PathSet,
    cmdopts: types.Cmdopts,
    info: bcbridge.GraphInfo,
) -> None:
    legend = "{}+{}".format(cmdopts["controller"], cmdopts["scenario"])

    paths = graphs.PathSet(
        input_root=pathset.stat_interexp_root,
        output_root=pathset.graph_interexp_root,
        batchroot=pathset.root,
        model_root=pathset.model_interexp_root,
    )

    # 2025-06-05 [JRH]: We always write stage {3,4} output data files as .csv
    # because that is currently SIERRA's 'native' format; this may change in the
    # future.
    graphs.summary_line(
        pathset=paths,
        input_stem=str(graph["dest"]),
        output_stem=str(graph["dest"]),
        medium="storage.csv",
        legend=[legend],
        stats=str(cmdopts.get("dist_stats", "none")),
        title=str(graph["title"]),
        xlabel=info.xlabel,
        ylabel=str(graph["ylabel"]),
        backend=str(graph.get("backend", cmdopts["graphs_backend"])),
        xticks=info.xticks,
        xticklabels=info.xticklabels,
        logyscale=bool(graph.get("logy", cmdopts["plot_log_yscale"])),
        large_text=cmdopts["plot_large_text"],
    )


def _gen_stacked_linegraph(
    graph: types.YAMLDict,
    pathset: batchroot.PathSet,
    cmdopts: types.Cmdopts,
    info: bcbridge.GraphInfo,
) -> None:

    paths = graphs.PathSet(
        input_root=pathset.stat_interexp_root,
        output_root=pathset.graph_interexp_root,
        model_root=None,
        batchroot=pathset.root,
    )

    graphs.stacked_line(
        pathset=paths,
        input_stem=str(graph["dest"]),
        output_stem=str(graph["dest"]),
        stats=str(cmdopts.get("dist_stats", "none")),
        medium="storage.csv",
        title=str(graph["title"]),
        backend=str(graph.get("backend", cmdopts["graphs_backend"])),
        xticks=None,
        xlabel=str(graph["xlabel"]),
        ylabel=str(graph["ylabel"]),
        logyscale=bool(graph.get("logy", cmdopts["plot_log_yscale"])),
        large_text=cmdopts["plot_large_text"],
        legend=tp.cast(
            "tp.Optional[list[str]]", graph.get("legend", info.exp_names)
        ),
    )


__all__ = ["generate"]
