#
# Copyright 2024 John Harwell, All rights reserved.
#
# SPDX-License-Identifier: MIT
#
"""Inter-experiment histogram generation in stage 4."""

# Core packages
import logging
import typing as tp

# 3rd party packages
import json

# Project packages
from sierra.core import types, batchroot, graphs
from sierra.core.graphs import bcbridge

_logger = logging.getLogger(__name__)


def generate(
    cmdopts: types.Cmdopts,
    pathset: batchroot.PathSet,
    targets: list[list[types.YAMLDict]],
    info: bcbridge.GraphInfo,
) -> None:
    """Generate scatterplots from :term:`Collated Output Data` files.

    The graphs generated by this module respect the ``--exp-range`` cmdline
    option.
    """

    _logger.info(
        "Scatterplots from <batchroot>/%s",
        pathset.stat_interexp_root.relative_to(pathset.root),
    )

    # For each category of scatterplots we are generating
    for category in targets:

        # For each graph in each category
        for graph in category:
            if graph["type"] != "scatterplot":
                continue

            _logger.trace("\n" + json.dumps(graph, indent=4))

            paths = graphs.PathSet(
                input_root=pathset.stat_interexp_root,
                output_root=pathset.graph_interexp_root,
                model_root=None,
                batchroot=pathset.root,
            )
            graphs.scatterplot(
                pathset=paths,
                input_stem=str(graph["dest"]),
                output_stem=str(graph["dest"]),
                medium="storage.csv",
                title=str(graph["title"]),
                backend=str(graph.get("backend", cmdopts["graphs_backend"])),
                xlabel=str(graph["xlabel"]),
                ylabel=str(graph["ylabel"]),
                large_text=cmdopts["plot_large_text"],
                stats_center=str(cmdopts.get("center", "mean")),
                xcol=None,
                ycol=None,
                show_best_fit=bool(graph["show_best_fit"]),
                best_fit_kind=str(graph["best_fit_kind"]),
                legend=tp.cast(
                    "tp.Optional[list[str]]", graph.get("legend", info.exp_names)
                ),
            )


__all__ = ["generate"]
