name: 'Setup SLURM'
description: 'Setup SLURM for CI and testing'
# inputs:
  # who-to-greet:  # id of input
  #   description: 'Who to greet'
  #   required: true
  #   default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - name: Install SLURM
      shell: bash
      run: |
        sudo apt update
        sudo apt-get install slurmd slurmctld -y

    - uses: nick-fields/retry@v3
      name: Configure SLURM
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          sudo mkdir -p /etc/slurm-llnl/
          sudo chmod 777 /etc/slurm-llnl
          sudo mkdir -p /var/lib/slurm-llnl/
          sudo mkdir -p /var/log/slurm-llnl/
          sudo chmod 777 /var/lib/slurm-llnl/
          sudo chmod 777 /var/log/slurm-llnl/

          sudo cp -f ./tests/smoke_tests/slurm.conf /etc/slurm-llnl/slurm.conf
          sudo cp -f ./tests/smoke_tests/slurm.conf /etc/slurm/slurm.conf

          sudo systemctl start slurmctld
          sudo systemctl start slurmd

          sudo scontrol update nodename=localhost state=IDLE

          # sudo systemctl status slurmctld.service
          # sudo journalctl -xe
          # sudo cat /var/log/slurm-llnl/slurmd.log
          # sudo cat /var/log/slurm-llnl/slurmctld.log
          # sinfo
