name: Publishing
description: Publish SIERRA to PyPI and Github

on:
  push:
    branches:
      - devel
      - master

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/sierra-setup
    - name: Build package
      run: |
        python3 -m build

    - name: Set tag
      if: github.ref == 'refs/heads/devel'
      run: echo "RELEASE_TAG=v$(python3 setup.py --version).beta" >> $GITHUB_ENV

    - name: Github beta release
      if: github.ref == 'refs/heads/devel'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.RELEASE_TAG }}
        prerelease: true
        title: "Development release ${{ env.RELEASE_TAG }}"

    - name: Publish to TestPyPI
      if: github.ref == 'refs/heads/devel'

      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Set tag
      if: github.ref == 'refs/heads/master'
      run: echo "RELEASE_TAG=v$(python3 setup.py --version)" >> $GITHUB_ENV

    - name: Github release
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.RELEASE_TAG }}
        prerelease: false
        title: "Release ${{ env.RELEASE_TAG }}"

    - name: Publish to PyPI
      if: github.ref == 'refs/heads/master'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
