# sim: Configuration keys specific to the simulation (not part of sierra)
sim:
  # metrics_leaf: The directory with the simulation working directory where
  # metrics are stored.
  metrics_leaf: 'metrics'

  # frames_leaf: The directory within the simulation working directory where
  # frames are stored
  frames_leaf: 'frames'

# sierra: Configuration keys are used by sierra to generate, run, and process
# simulation results
sierra:
  # Directory within the batch experiment root to hold collated .csvs
  collate_csv_leaf: 'collated-csvs'

  # Directory within the batch experiment root to hold collated graphs
  collate_graph_leaf: 'collated-graphs'

  # Directory with each experiment's directory for holding averaged .csvs
  avg_output_leaf: 'averaged-output'

  # perf: Configuration keys are used by sierra for performance metric
  # calculation. Right now, they are still somewhat tied to fordyca.
  perf:
    blocks_collected_csv: 'blocks-collected-cum.csv'
    ca_cum_csv: 'ca-in-cum-avg.csv'
    temporal_var_csv: 'loop-temporal-variance.csv'
