# Intra-scenario
intra_scenario:
  graphs:
    - src_stem: pm-scalability-fl
      dest_stem: cc-pm-scalability-fl
      title: 'Swarm Scalability (Sub-Linear Fractional Losses)'
      label: 'Scalability Value'


    - src_stem: pm-scalability-norm
      dest_stem: cc-pm-scalability-norm
      title: 'Swarm Scalability (Normalized)'
      label: 'Scalability Value'


    - src_stem: pm-self-org-fl
      dest_stem: cc-pm-self-org-fl
      title: 'Swarm Self Organization'
      label: 'Self Organization Value'


    - src_stem: pm-blocks-collected-cum
      dest_stem: cc-pm-blocks-collected-cum
      title: 'Swarm Performance'
      label: 'Total Blocks Collected'

    - src_stem: pm-karpflatt
      dest_stem: cc-pm-karpflatt
      title: 'Swarm Scalability (Karp-Flatt)'
      label: 'Karp-Flatt Value'
