# Intra-scenario
intra_scenario:
  graphs:
    - src_stem: pm-scalability-fl
      dest_stem: cc-pm-scalability-fl
      title: 'Swarm Scalability (Sub-Linear Fractional Losses)'
      label: 'Scalability Value'


    - src_stem: pm-scalability-norm
      dest_stem: cc-pm-scalability-norm
      title: 'Swarm Scalability (Normalized)'
      label: 'Scalability Value'


    - src_stem: pm-self-org
      dest_stem: cc-pm-self-org
      title: 'Swarm Self Organization'
      label: 'Self Organization Value'


    - src_stem: pm-blocks-collected-cum
      dest_stem: cc-pm-blocks-collected-cum
      title: 'Swarm Performance'
      label: 'Total Blocks Collected'

    - src_stem: pm-karpflatt
      dest_stem: cc-pm-karpflatt
      title: 'Swarm Scalability (Karp-Flatt)'
      label: 'Karp-Flatt Value'

# Inter-scenario
inter_scenario:
  graphs:
    - src_stem: pm-scalability-fl
      dest_stem: sc-pm-scalability-fl
      title: 'Swarm Scalability (Karp-Flatt)'


    - src_stem: pm-scalability-norm
      dest_stem: sc-pm-scalability-norm
      title: 'Swarm Scalability (Normalized)'


    - src_stem: pm-self-org
      dest_stem: sc-pm-self-org
      title: 'Swarm Self Organization'


    - src_stem: pm-blocks-collected-cum
      dest_stem: sc-pm-blocks-collected-cum
      title: 'Swarm Performance'


    - src_stem: pm-adaptability
      dest_stem: sc-pm-adaptability
      title: 'Swarm Adaptability'


    - src_stem: pm-reactivity
      dest_stem: sc-pm-reactivity
      title: 'Swarm Reactivity'
