name: 'Setup SIERRA'
description: 'Setup SIERRA for CI and testing'
runs:
  using: 'composite'
  steps:

    ############################################################################
    # Common setup
    ############################################################################
    - name: Setup python (all OSes)
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install python packages (all OSes)
      shell: bash
      run: |
        python3 --version
        which python3
        python3 -m pip install wheel
        python3 -m pip install -r docs/requirements.txt

    - uses: kenchan0130/actions-system-info@master
      id: system-info

    ############################################################################
    # Ubuntu setup
    ############################################################################
    - name: Install+cache system packages (ubuntu)
      if: runner.os == 'Linux'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: parallel cm-super dvipng pssh ffmpeg xvfb
        version: ${{ runner.os }}

    # 2024/09/24: Needed because caching + texlive don't play well
    # together. There IS an "install texlive" action, but that requires manual
    # specification of all packages needed, and it seem easier to just use the
    # package manager to recursively pull in everything I would need.
    - name: Install system packages (redundant, ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt update && sudo apt-get install -y texlive-fonts-recommended texlive-latex-extra

    ############################################################################
    # OSX setup
    ############################################################################
    - name: Enable homebrew (OSX)
      if: runner.os == 'macOS'
      uses: Homebrew/actions/setup-homebrew@master

    - uses: nick-fields/retry@v2
      name: Install system deps (OSX)
      if: runner.os == 'macOS'
      with:
        timeout_minutes: 10000
        max_attempts: 3
        shell: bash
        command: |
          python3 --version
          which python3

          brew update
          brew install parallel pssh

    # 2024-12-12 [JRH]: We have to do this after installing homebrew packages,
    # because if any of the packages update/install python, then we start
    # picking up the system python/homebrew python instead of the one we want
    # which we setup earlier.
    - name: Re-setup python (OSX)
      if: runner.os == 'macOS'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    ############################################################################
    # SIERRA install
    ############################################################################
    - name: Install SIERRA
      shell: bash
      run: |
        python3 --version
        which python3

        cd docs && make man && cd ..

        # 2024-12-12 [JRH]: This is necessary on OSX until msgspec releases the
        # necessary package in pypi; not a problem on linux.
        python3 -m pip install git+https://github.com/jcrist/msgspec.git@main

        python3 -m pip install .
        python3 -m pip install .[devel]

        which sierra-cli
        sierra-cli --version
