name: 'Setup SIERRA'
description: 'Setup SIERRA for CI and testing'
# inputs:
  # who-to-greet:  # id of input
  #   description: 'Who to greet'
  #   required: true
  #   default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:

    ############################################################################
    # Ubuntu setup
    ############################################################################
    - name: Setup python (ubuntu)
      uses: actions/setup-python@v4
      if: runner.os == 'Linux'
      with:
        python-version: ${{ matrix.python-version }}

    # - uses: Setup python (ubuntu)
    #   if: runner.os == 'Linux'
    #   shell: bash
    #   run: |
    #     # apt fails randomly on microsoft's azure servers...
    #     sudo sed -i 's/azure\.//' /etc/apt/sources.list
    #     sudo add-apt-repository -y ppa:deadsnakes/ppa

    #     sudo apt-get update

    #     sudo apt-get install python${{ matrix.python-version }} python${{ matrix.python-version }}-dev
    #     sudo apt-get install python${{ matrix.python-version }}-venv python3-apt
    #     sudo apt-get install python3-pip python3-cairo intltool python3-wheel strace
    #     sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${{ matrix.python-version }} 1

    #     # HACK HACK HACK!
    #     sudo ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-38-x86_64-linux-gnu.so  /usr/lib/python3/dist-packages/apt_pkg.so
    #     sudo ln -s /usr/lib/python3/dist-packages/netifaces.cpython-38-x86_64-linux-gnu.so  /usr/lib/python3/dist-packages/netifaces.so


    - name: Install system deps (ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install parallel cm-super texlive-fonts-recommended
        sudo apt-get install texlive-latex-extra dvipng pssh ffmpeg xvfb
        python3 -m pip install --upgrade pip
        python3 -m pip install wheel

    ############################################################################
    # OSX setup
    ############################################################################

    - name: Setup python (OSX)
      uses: actions/setup-python@v4
      if: runner.os == 'macOS'
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system deps (OSX)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        # 2023/01/16: || true needed because homebrew installation of whatever
        # dependencies these packages requires manual intervention to fix, and I
        # don't have a mac.
        brew install parallel pssh ffmpeg || true
        brew install --cask mactex || true
        brew install --cask xquartz || true
        python -m pip install --upgrade pip
        python -m pip install wheel

    ############################################################################
    # SIERRA install
    ############################################################################
    - name: Install SIERRA
      shell: bash
      run: |
        python -m pip install -r docs/requirements.txt
        cd docs && make man && cd ..
        python3 -m pip install .
        python3 -m pip install .[devel]

        which sierra-cli
        sierra-cli --version
