from variables import arena_shape
from variables import block_distribution
from variables import nest_pose
from variables import constant_density
from variables import swarm_size
from variables import temporal_variance
from variables import static_cache
from variables import physics_engines
from variables import temporal_variance_parser
from variables import batch_criteria
