# Copyright 2018 London Lowmanstone, John Harwell, All rights reserved.
#
#  This file is part of SIERRA.
#
#  SIERRA is free software: you can redistribute it and/or modify it under the
#  terms of the GNU General Public License as published by the Free Software
#  Foundation, either version 3 of the License, or (at your option) any later
#  version.
#
#  SIERRA is distributed in the hope that it will be useful, but WITHOUT ANY
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
#  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with
#  SIERRA.  If not, see <http://www.gnu.org/licenses/
"""
Experiment generation classes, generating definitions common to all batched experiments, as well as
definitions generated by the controller+scenario. Generated definitions from batch criteria are not
handled here.
"""


import os
import pickle
import typing as tp
import logging

from core.xml_luigi import XMLLuigi
from core.variables import camera_timeline
import core.generators.generator_factory as gf
import core.xml_luigi
from core.experiment_spec import ExperimentSpec


class ExpDefCommonGenerator:
    """
    Base class for generating sets of changes to a template input file that will form the definition
    for a single experiment within a batch that are common to all types of batch
    experiments. Changes for:

      - visualizations
      - threading
      - simulation time parameters
      - Disabling sensors and actuators
      - Simulation length

    Attributes:
        template_input_file: Path(relative to current dir or absolute) to the template XML
                             configuration file.
        cmdopts: Dictionary containing parsed cmdline options.
    """

    def __init__(self,
                 spec: ExperimentSpec,
                 template_input_file: str,
                 cmdopts: dict) -> None:

        self.template_input_file = os.path.abspath(template_input_file)
        self.cmdopts = cmdopts
        self.spec = spec

    def generate(self):
        """
        Generates XML changes to simulation input files that are common to all experiments.
        """
        # create an object that will edit the XML file
        xml_luigi = XMLLuigi(self.template_input_file)

        # Setup library
        self._generate_library(xml_luigi)

        # Setup simulation visualizations
        self._generate_visualization(xml_luigi)

        # Setup threading
        self._generate_threading(xml_luigi)

        # Setup robot sensors/actuators
        self._generate_saa(xml_luigi)

        # Setup simulation time parameters
        self._generate_time(xml_luigi)

        return xml_luigi

    def _generate_saa(self, xml_luigi: XMLLuigi):
        """
        Generates XML changes to disable selected sensors/actuators, which are computationally
        expensive in large swarms, but not that costly if the # robots is small.

        Does not write generated changes to the simulation definition pickle file.
        """
        if not self.cmdopts["with_robot_rab"]:
            xml_luigi.tag_remove(".//media", "range_and_bearing", noprint=True)
            xml_luigi.tag_remove(".//actuators", "range_and_bearing", noprint=True)
            xml_luigi.tag_remove(".//sensors", "range_and_bearing", noprint=True)

        if not self.cmdopts["with_robot_leds"]:
            xml_luigi.tag_remove(".//actuators", "leds", noprint=True)
            xml_luigi.tag_remove(".//sensors", "colored_blob_omnidirectional_camera", noprint=True)
            xml_luigi.tag_remove(".//medium", "leds", noprint=True)

        if not self.cmdopts["with_robot_battery"]:
            xml_luigi.tag_remove(".//sensors", "battery", noprint=True)
            xml_luigi.tag_remove(".//entity/*", "battery", noprint=True)

    def _generate_time(self, xml_luigi: XMLLuigi):
        """
        Generate XML changes to setup simulation time parameters.

        Writes generated changes to the simulation definition pickle file.
        """
        setup = __import__("core.variables.{0}".format(
            self.cmdopts["time_setup"].split(".")[0]), fromlist=["*"])
        tsetup_inst = getattr(setup, "factory")(self.cmdopts["time_setup"])()

        for a in tsetup_inst.gen_attr_changelist()[0]:
            xml_luigi.attr_change(a.path, a.attr, a.value, True)

        # Write time setup info to file for later retrieval
        tsetup_inst.gen_attr_changelist()[0].pickle(self.spec.exp_def_fpath)

    def _generate_threading(self, xml_luigi: XMLLuigi):
        """
        Generates XML changes to set the # of cores for a simulation to use, which may be less than
        the total # available on the system, depending on the experiment definition and user
        preferences.

        Does not write generated changes to the simulation definition pickle file.
        """

        xml_luigi.attr_change(".//system",
                              "threads",
                              str(self.cmdopts["physics_n_engines"]))

        # This whole tree can be missing and that's fine
        if xml_luigi.has_tag(".//loop_functions/convergence"):
            xml_luigi.attr_change(".//loop_functions/convergence",
                                  "n_threads",
                                  str(self.cmdopts["physics_n_engines"]))

    def _generate_library(self, xml_luigi: XMLLuigi):
        """
        Generates XML changes to set the library that controllers and loop functions are sourced
        from to the name of the plugin passed on the cmdline. The ``__controller__`` tag is changed
        during stage 1, but since this function is called as part of common def generation, it
        happens BEFORE that, and so this is OK. If, for some reason that assumption becomes invalid,
        a warning will be issued about a non-existent XML path, so it won't be a silent error.

        Does not write generated changes to the simulation definition pickle file.
        """
        xml_luigi.attr_change(".//loop_functions",
                              "library",
                              "lib" + self.cmdopts['project'])
        xml_luigi.attr_change(".//__controller__",
                              "library",
                              "lib" + self.cmdopts['project'])

    def _generate_visualization(self, xml_luigi: XMLLuigi):
        """
        Generates XML changes to remove visualization elements from input file, if configured to do
        so. This depends on cmdline parameters, as visualization definitions should be left in if
        ARGoS should output simulation frames for video creation.

        Does not write generated changes to the simulation definition pickle file.
        """
        if not self.cmdopts["argos_rendering"]:
            xml_luigi.tag_remove(".", "./visualization", noprint=True)  # ARGoS visualizations
        else:
            cams = camera_timeline.factory(self.cmdopts, [self.cmdopts['arena_dim']])
            rms = cams.gen_tag_rmlist()[0]
            if rms:
                for r in rms:
                    xml_luigi.tag_remove(r.path, r.tag, True)  # OK if camera stuff isn't there

            for a in cams.gen_tag_addlist()[0]:
                xml_luigi.tag_add(a.path, a.tag, a.attr)


class BatchedExpDefGenerator:
    """
    Class for generating experiment definitions for a batched experiment. Does not create the
    batched experiment after generation.

    Attributes:
        batch_config_template: Path (relative to current dir or absolute) to the root template
                               XML configuration file.

        batch_input_root: Root directory for all generated XML input files all experiments
                               should be stored (relative to current dir or absolute). Each
                               experiment will get a directory within this root to store the xml
                               input files for the simulation runs comprising an experiment;
                               directory name determined by the batch criteria used.

        batch_output_root: Root directory for all experiment outputs (relative to current dir or
                           absolute). Each experiment will get a directory 'exp<n>' in this
                           directory for its outputs.

        criteria: :class:`~core.variables.batch_criteria.BatchCriteria` derived object instance
                  created from cmdline definition.
        controller_name: Name of controller generator to use.
        scenario_basename: Name of scenario generator to use.
    """

    def __init__(self,
                 batch_config_template: str,
                 criteria,
                 controller_name: str,
                 scenario_basename: str,
                 cmdopts: dict) -> None:
        assert os.path.isfile(
            batch_config_template), \
            "The path '{}' (which should point to the main config file) did not point to a file".format(
                batch_config_template)
        self.batch_config_template = os.path.abspath(batch_config_template)
        self.batch_config_leaf, _ = os.path.splitext(
            os.path.basename(self.batch_config_template))
        self.batch_config_extension = None

        self.batch_input_root = os.path.abspath(cmdopts['batch_input_root'])
        assert self.batch_input_root.find(" ") == -1, \
            ("ARGoS (apparently) does not work with input file paths with spaces. Please make sure the " +
             "batch input root directory '{}' does not have any spaces in it").format(self.batch_input_root)

        self.batch_output_root = os.path.abspath(cmdopts['batch_output_root'])

        self.controller_name = controller_name
        self.scenario_basename = scenario_basename
        self.criteria = criteria
        self.cmdopts = cmdopts
        self.logger = logging.getLogger(__name__)

    def generate_defs(self) -> tp.List[core.xml_luigi.XMLLuigi]:
        """
        Generates and returns a list of experiment definitions (one for each experiment in the batch),
        which can used to create the batched experiment.
        """
        change_defs = self.criteria.gen_attr_changelist()

        # Create and run generators
        defs = []
        for i in range(0, len(change_defs)):
            generator = self._create_exp_generator(i)
            defs.append(generator.generate())
            self.logger.debug("Generating scenario+controller changes from generator '%s' for exp%s",
                              self.cmdopts['joint_generator'],
                              i)

        return defs

    def _create_exp_generator(self, exp_num: int):
        """
        Create the generator for a particular experiment from the scenario+controller definitions
        specified on the command line.

        Arguments:
            exp_num: Experiment number in the batch
        """

        spec = ExperimentSpec(self.criteria, exp_num, self.cmdopts)

        scenario = gf.scenario_generator_create(controller=self.controller_name,
                                                spec=spec,
                                                template_input_file=os.path.join(spec.exp_input_root,
                                                                                 self.batch_config_leaf),
                                                cmdopts=self.cmdopts)

        controller = gf.controller_generator_create(controller=self.controller_name,
                                                    config_root=self.cmdopts['project_config_root'],
                                                    cmdopts=self.cmdopts)

        self.cmdopts['joint_generator'] = '+'.join([controller.__class__.__name__,
                                                    scenario.__class__.__name__])

        return gf.joint_generator_create(scenario=scenario,
                                         controller=controller)


__api__ = [
    'ExpDefCommonGenerator',
    'BatchedExpDefGenerator',
]
