name: OS Static Analysis

on:
  workflow_call:
    inputs:
      container:
        required: True
        type: string

jobs:
  nox:
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.12

        session:
          - docs
          - analyze_pytype
          - analyze_mypy
          - analyze_misc
          - analyze_ruff


    steps:
      - uses: actions/checkout@v3
      - name: Run nox
        run: |
          uv run -p ${{ matrix.python-version }} nox \
            --pythons ${{ matrix.python-version }} \
            --sessions ${{ matrix.session }}
