name: ARGoS CI

on:
  push:
    branches:
      # - master
      # - devel
    paths:
      - 'sierra/**'

jobs:
  argos-platform:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - name: ARGoS platform integration tests
        run: |
          ./scripts/argos-integration-tests.sh
