# Only stuff that actually tests the platform should be here: stage 1 and 2.
name: ARGoS CI Tests

on:
  workflow_call:
    inputs:
      os:
        required: True
        type: string

jobs:
  bc-univar-sanity:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: nick-fields/retry@v2
        name: Integration tests
        with:
          timeout_minutes: 3600
          max_attempts: 3
          shell: bash
          command: ./scripts/argos-integration-tests.sh -f bc_univar_sanity_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-argos-bc-univar-sanity-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*

  physics-engines:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: nick-fields/retry@v2
        name: Integration tests
        with:
          timeout_minutes: 3600
          max_attempts: 3
          shell: bash
          command: ./scripts/argos-integration-tests.sh -f physics_engines_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-argos-physics-engines-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*

  stage1-univar:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: nick-fields/retry@v2
        name: Integration tests
        with:
          timeout_minutes: 3600
          max_attempts: 3
          shell: bash
          command: ./scripts/argos-integration-tests.sh -f stage1_univar_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-argos-stage1-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*

  stage2-univar:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: nick-fields/retry@v2
        name: Integration tests
        with:
          timeout_minutes: 3600
          max_attempts: 3
          shell: bash
          command: ./scripts/argos-integration-tests.sh -f stage2_univar_test -e hpc.local

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-argos-stage2-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*


  visual-capture:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: nick-fields/retry@v2
        name: Integration tests
        with:
          timeout_minutes: 3600
          max_attempts: 3
          shell: bash
          command: ./scripts/argos-integration-tests.sh -f vc_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-argos-vc-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*

  cmdline:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: nick-fields/retry@v2
        name: Integration tests
        with:
          timeout_minutes: 3600
          max_attempts: 3
          shell: bash
          command: ./scripts/argos-integration-tests.sh -f cmdline_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-argos-cmdline-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*
