name: ARGoS CI

on:
  workflow_call:
  # push:
  #   branches:
  #     # - master
  #     # - devel
  #   paths:
  #     - 'sierra/**'

jobs:
  batch-criteria:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - name: Integration tests
        run: |
          ./scripts/argos-integration-tests.sh --func batch_criteria_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-argos-batch-criteria-${{ matrix.python-version }}-coverage
          path: .coverage

  physics-engines:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - name: Integration tests
        run: |
          ./scripts/argos-integration-tests.sh --func physics_engines_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-argos-physics-engines-${{ matrix.python-version }}-coverage
          path: .coverage

  stage1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - name: Integration tests
        run: |
          ./scripts/argos-integration-tests.sh --func stage1_outputs_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-argos-stage1-${{ matrix.python-version }}-coverage
          path: .coverage

  stage2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/slurm-setup
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - name: Integration tests
        run: |
          ./scripts/argos-integration-tests.sh --func stage2_outputs_test --env=hpc.local

      - uses: actions/upload-artifact@v3
        with:
          name: ci-argos-stage2-${{ matrix.python-version }}-coverage
          path: .coverage

  stage3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - name: Integration tests
        run: |
          ./scripts/argos-integration-tests.sh --func stage3_outputs_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-argos-stage3-${{ matrix.python-version }}-coverage
          path: .coverage

  stage4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - name: Integration tests
        run: |
          ./scripts/argos-integration-tests.sh --func stage4_outputs_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-argos-stage4-${{ matrix.python-version }}-coverage
          path: .coverage
