name: Coverage CI

# Run:
#
# - Every month.  Scheduling helps keep drift/issues with updates
#   to runners at bay.
# - On pushes.
on:
  push:
    paths:
      - 'sierra/**'
  schedule:
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  argos-ci:
    uses: ./.github/workflows/argos.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  ros1gazebo-ci:
    uses: ./.github/workflows/ros1gazebo.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  sierra-core-ci:
    uses: ./.github/workflows/sierra-core.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  ros1robot-ci:
    uses: ./.github/workflows/ros1robot.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  exec-env-ci:
    uses: ./.github/workflows/exec-env-plugins.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8

    needs:
      - unit-tests
      - argos-ci
      - ros1gazebo-ci
      - ros1robot-ci
      - exec-env-ci
      - sierra-core-ci

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: actions/download-artifact@v3

      - name: Generate coverage report
        run: |

          coverage combine ci-*-Linux-${{ matrix.python-version }}-coverage/.coverage.*  ci-*-Linux-${{ matrix.python-version }}-coverage/.coverage

          coverage report
          coverage xml

      - uses: actions/upload-artifact@v3
        with:
          name: ci-integration-coverage

          path: .coverage

      - uses: actions/upload-artifact@v3
        with:
          name: ci-integration-coverage-xml
          path: coverage.xml

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

        run: |
          coveralls
