name: --exec-env plugin CI

on:
  workflow_call:
    inputs:
      os:
        required: True
        type: string

  # push:
  #   branches:
  #     # - master
  #     # - devel
  #   paths:
  #     - 'sierra/**'

jobs:

  adhoc:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        # You CANNOT use python 3.9 with ubuntu 20.04 with ROS, because 3.8 is
        # the system python and things just don't work otherwise...
        python-version:
          - 3.8

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: ./.github/actions/sample-project-setup
        with:
          platform: ros1gazebo
          rosdistro: noetic

      - name: Adhoc
        run: |
          ./scripts/argos-integration-tests.sh -f stage2_univar_test -e hpc.adhoc
          ./scripts/ros1gazebo-integration-tests.sh -f stage2_univar_test -e hpc.adhoc

      - uses: actions/upload-artifact@v3
        with:
          name: ci-exec-env-adhoc-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*

  slurm:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        # You CANNOT use python 3.9 with ubuntu 20.04 with ROS, because 3.8 is
        # the system python and things just don't work otherwise...
        python-version:
          - 3.8

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/sierra-setup

      - uses: ./.github/actions/slurm-setup

      - uses: ./.github/actions/sample-project-setup
        with:
          platform: argos

      - uses: ./.github/actions/sample-project-setup
        with:
          platform: ros1gazebo
          rosdistro: noetic

      - name: SLURM
        run: |
          ./scripts/argos-integration-tests.sh -f stage2_univar_test -e hpc.slurm
          ./scripts/ros1gazebo-integration-tests.sh -f stage2_univar_test -e hpc.slurm

      - uses: actions/upload-artifact@v3
        with:
          name: ci-exec-env-slurm-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*
