name: Integration Tests

# Run:
#
# - Every month. Scheduling helps keep drift/issues with updates
#   to runners at bay.
# - On pushes.
on:
  push:
    paths:
      - 'sierra/**'

  schedule:
    - cron: '0 0 1 * *'

jobs:
  argos-ci-ubuntu:
    uses: ./.github/workflows/argos.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  argos-ci-osx:
    uses: ./.github/workflows/argos.yml
    secrets: inherit
    with:
      os: macos-12

  sierra-core-ci-ubuntu:
    uses: ./.github/workflows/sierra-core.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  sierra-core-ci-osx:
    uses: ./.github/workflows/sierra-core.yml
    secrets: inherit
    with:
      os: macos-12

  ros1gazebo-ci-ubuntu:
    uses: ./.github/workflows/ros1gazebo.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  ros1robot-ci-ubuntu:
    uses: ./.github/workflows/ros1robot.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  exec-env-ci-ubuntu:
    uses: ./.github/workflows/exec-env-plugins.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
    needs:
      - argos-ci-ubuntu
      - argos-ci-osx
      - sierra-core-ci-ubuntu
      - sierra-core-ci-osx
      - ros1gazebo-ci-ubuntu
      - ros1robot-ci-ubuntu
      - exec-env-ci-ubuntu

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
          testpypi-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
