name: Plugins CI

on:
  push:
    branches:
      # - master
      # - devel
    paths:
      - 'sierra/**'

jobs:
  argos-ci-ubuntu:
    uses: ./.github/workflows/argos.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  argos-ci-osx:
    uses: ./.github/workflows/argos.yml
    secrets: inherit
    with:
      os: macos-12

  ros1gazebo-ci-ubuntu:
    uses: ./.github/workflows/ros1gazebo.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  exec-env-ci-ubuntu:
    uses: ./.github/workflows/exec-env-plugins.yml
    secrets: inherit
    with:
      os: ubuntu-20.04

  publish:
    runs-on: ubuntu-latest
    needs:
      - argos-ci-ubuntu
      - argos-ci-osx
      - ros1gazebo-ci-ubuntu
      - exec-env-ci-ubuntu

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/publish
