name: Plugins CI

on:
  push:
    branches:
      # - master
      # - devel
    paths:
      - 'sierra/**'

jobs:
  argos-ci:
    uses: ./.github/workflows/argos-integration.yml
    secrets: inherit

  ros1gazebo-ci:
    uses: ./.github/workflows/ros1gazebo-integration.yml
    secrets: inherit

  exec-env-ci:
    uses: ./.github/workflows/exec-env-integration.yml
    secrets: inherit

  coverage:
    runs-on: ubuntu-latest
    needs: [argos-ci, ros1gazebo-ci, exec-env-ci]
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-argos-batch-criteria-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-argos-physics-engines-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-argos-stage1-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-argos-stage2-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-argos-stage3-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-argos-stage4-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-ros1gazebo-batch-criteria-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-ros1gazebo-stage2-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-exec-env-adhoc-${{ matrix.python-version }}-coverage

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: ci-exec-env-slurm-${{ matrix.python-version }}-coverage

      - name: Generate coverage report
        run: |
          # ls -alh .
          # ls -alh ci-*
          # ls -alh ci-*-${{ matrix.python-version }}-coverage/ || true
          # ls -alh ci-*-${{ matrix.python-version }}-coverage/.coverage || true

          coverage combine ci-*-${{ matrix.python-version }}-coverage/.coverage

          coverage report
          coverage xml

      - uses: actions/upload-artifact@v3
        with:
          name: ci-integration-coverage
          path: coverage.xml

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

        run: |
          coveralls
