name: ROS1+Gazebo CI

on:
  push:
    branches:
      # - master
      # - devel

    paths:
      - 'sierra/**'

jobs:
  ros1gazebo-platform:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup
      - uses: ./.github/actions/sample-project-setup
        with:
          platform: ros1gazebo

      - name: ROS1+Gazebo platform integration tests (noetic)
        run: |
          ./scripts/ros1gazebo-integration-tests.sh noetic
