# Only stuff that actually tests the platform should be here: stage 1 and 2.
name: ROS1+Gazebo CI Tests

on:
  workflow_call:
    inputs:
      os:
        required: True
        type: string

jobs:
  bc-univar-sanity:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        # You CANNOT use python 3.9 with ubuntu 20.04 with ROS, because 3.8 is
        # the system python and things just don't work otherwise...
        python-version:
          - 3.8

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/sierra-setup

      - uses: ./.github/actions/sample-project-setup
        with:
          platform: ros1gazebo
          rosdistro: noetic

      - name: Integration tests
        shell: bash
        run: |
          ./scripts/ros1gazebo-integration-tests.sh -f bc_univar_sanity_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-ros1gazebo-bc-univar-sanity-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*

  stage2-univar:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        # You CANNOT use python 3.9 with ubuntu 20.04 with ROS, because 3.8 is
        # the system python and things just don't work otherwise...
        python-version:
          - 3.8

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/sierra-setup

      - uses: ./.github/actions/sample-project-setup
        with:
          platform: ros1gazebo
          rosdistro: noetic

      - name: Integration tests
        shell: bash
        run: |
          ./scripts/ros1gazebo-integration-tests.sh -f stage2_univar_test -e hpc.local

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-ros1gazebo-stage2-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*
