name: ROS1+Gazebo CI Tests

on:
  workflow_call:
    inputs:
      os:
        required: True
        type: string
  # push:
  #   branches:
  #     # - master
  #     # - devel
  #   paths:
  #     - 'sierra/**'

jobs:
  batch-criteria:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/sierra-setup

      - uses: ./.github/actions/sample-project-setup
        with:
          platform: ros1gazebo
          rosdistro: noetic

      - name: Integration tests
        shell: bash
        run: |
          ./scripts/ros1gazebo-integration-tests.sh -f batch_criteria_test

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-ros1gazebo-batch-criteria-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*

  stage2:
    runs-on: ${{ inputs.os }}
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/sierra-setup

      - uses: ./.github/actions/sample-project-setup
        with:
          platform: ros1gazebo
          rosdistro: noetic

      - name: Integration tests
        shell: bash
        run: |
          ./scripts/ros1gazebo-integration-tests.sh -f stage2_test -e hpc.local

      - uses: actions/upload-artifact@v3
        with:
          name: ci-platform-ros1gazebo-stage2-${{ runner.os }}-${{ matrix.python-version }}-coverage
          path: .coverage.*
