name: Static Analysis

# Run:
#
# - Every month.  Scheduling helps keep drift/issues with updates
#   to runners at bay.
# - On pushes.
on:
  push:
    paths:
      - 'sierra/**'
  schedule:
    - cron: '0 0 1 * *'


jobs:
  analyze:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04 # ubuntu-latest, as of 8/22
          - macos-12

        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup

      - name: Run nox
        run: |
          nox --pythons ${{ matrix.python-version }} --sessions lint analysis docs
