name: Static analysis CI

on:
  push:
    branches:
      # - master
      # - devel

    paths:
      - 'sierra/**'

jobs:
  sierra-analyze:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup

      - name: Install nox
        run: |
          pip3 install nox

      - name: Run nox
        run: |
          nox --pythons ${{ matrix.python-version }}
