name: Static Analysis

on:
  workflow_call:
  push:
    paths:
      - 'sierra/**'

jobs:
  analyze:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04 # ubuntu-latest, as of 8/22
          - macos-12

        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup

      - name: Run nox
        run: |
          nox --pythons ${{ matrix.python-version }} --sessions lint analysis docs
