name: Static analysis

on:
  push:
    branches:
      - master
      - devel

jobs:
  sierra-analyze:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sierra-setup

      - name: Install checkers
        run: |
          pip3 install flake8 mypy pylint pytype

      - name: Check with flake8
        run: |

          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127
          # chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics

      - name: Check with pytype
        run: |
          pytype -d name-error,attribute-error,invalid-annotation,pyi-error sierra

      - name: Check with pylint
        run: |
          # Anything less than a 'B' is bad
          pylint sierra
